name: Flutter APK build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.7.9

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Build APK file
        run: flutter build apk

      - name: Create GitHub Release
        uses: softprops/create-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'

      - name: Add APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/apk/release/app-release.apk
          asset_name: ratiocalci.apk
          asset_content_type: application/vnd.android.package-archive
