# name: Flutter APK build

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Flutter SDK
#         uses: flutter-actions/setup-flutter@v3
#         with:
#           channel: stable
#           version: 3.7.9

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Analyze project source
#         run: dart analyze

#       - name: Build APK file
#         run: flutter build apk
        
#       # - name: Add to release tag
#       #   uses: sangatdesai/release-apk@main
#       #   env:
#       #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
#       #     APP_FOLDER: build/app/outputs/flutter-apk/app-release.apk

#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#             artifacts: build/app/outputs/flutter-apk/app-release.apk
#             tag: v0.0.1
#             token: $ {{ secrets.TOKEN }}

on:
  push:
    branches:
      - master

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.7.9
      - run: flutter pub get
      - run: flutter build apk

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}
